DROP TABLE IF EXISTS reviews CASCADE;

CREATE TABLE reviews (
  id SERIAL PRIMARY KEY NOT NULL,
  customer_id INTEGER REFERENCES customers(id) ON DELETE CASCADE,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  review_date TIMESTAMP NOT NULL DEFAULT now(),
  rating INTEGER NOT NULL,
  comment VARCHAR (225) NOT NULL
);
